
export const _TYPES_PICTURES_ = [
    {value:"animals", label:"animals"},
    {value:"panorama", label:"panorama"},
    {value:"cars", label:"cars"},
    {value:"abstract_painting", label:"abstract"},
    {value:"manga", label:"manga"},
    {value:"realistic", label:"realistic"},
    {value:"architecture", label:"architecture"},
    {value:"bd", label:"bd"},
    {value:"people", label:"people"},
    {value:"cultural", label:"cultural"},
    {value:"painting", label:"painting"},
    {value:"family", label:"family"},
    {value:"building", label:"building"},
    {value:"themes", label:"themes"},
    {value:"famous", label:"famous"},
    {value:"city", label:"city"},
    {value:"lake", label:"lake"},
    {value:"pixar", label:"pixar"},
    {value:"lego", label:"lego"},
    {value:"sport", label:"sport"},
    {value:"drilldev", label:"drilldev"},
    {value:"kids", label:"kids"},
    {value:"portrait", label:"portait"},
    {value:"country", label:"country"},
    {value:"art martial", label:"art martial"},
    {value:"planet", label:"planet"},
    {value:"fruits", label:"fruits"},
    {value:"veggies", label:"veggies"},
    {value:"music", label:"music"},
    {value:"instruments", label:"instruments"},
    {value:"clothes", label:"clothes"},
];